using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace AxpPortal.DtoGenerator;

[Generator]
public sealed class PocosModelGenerator : IIncrementalGenerator
{
    private const string ContractsNamespace = "T4.AxClient.Contracts";
    private const string TargetSourceFileName = "_AxpPocoGen_AxpPortalApiService.cs";

    private const string ModelNamespace = "T4.AxClient.Model";

    private static ApiBaseClassMapping[] ClassMappings = [
        new("AxpPortalApiUserKey", true),

        new("AxpPortalApiRequstBase", true, GenBuildApiRequest1),
        new("AxpPortalApiAuthorisedRequstBase", true, GenBuildApiRequest2),
        new("AxpPortalApiResponseBase", false, GenBuildApiRequest3),
    ];

    private static string GenBuildApiRequest1(ClassCandidate candidate, IReadOnlyDictionary<string, ClassCandidate> map)
    {
        StringBuilder sb = new();
        sb.AppendLine($"        public {ContractsNamespace}.{candidate.ClassName} BuildApiRequest(string portalWebsiteId)");
        sb.AppendLine(@"        {");
        sb.AppendLine($"            return new {ContractsNamespace}.{candidate.ClassName}");
        sb.AppendLine(@"            {");
        sb.AppendLine(@"                PortalWebsiteId = portalWebsiteId,");
        sb.AppendLine();

        foreach (var property in candidate.Properties)
        {
            var propertyName = property.Identifier.Text;
            sb.AppendLine($"                {propertyName} = this.{propertyName},");
        }

        sb.AppendLine(@"            };");
        sb.AppendLine(@"        }");

        return sb.ToString();
    }

    private static string GenBuildApiRequest2(ClassCandidate candidate, IReadOnlyDictionary<string, ClassCandidate> map)
    {
        StringBuilder sb = new();
        sb.AppendLine($"        public {ContractsNamespace}.{candidate.ClassName} BuildApiRequest(string portalWebsiteId, {ContractsNamespace}.AxpPortalApiUserKey userKey)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new {ContractsNamespace}.{candidate.ClassName}");
        sb.AppendLine(@"            {");
        sb.AppendLine(@"                PortalWebsiteId = portalWebsiteId,");
        sb.AppendLine(@"                UserKey = userKey,");
        sb.AppendLine();

        foreach (var property in candidate.Properties)
        {
            var propertyName = property.Identifier.Text;
            sb.AppendLine($"                {propertyName} = this.{propertyName},");
        }

        sb.AppendLine(@"            };");
        sb.AppendLine("        }");

        return sb.ToString();
    }

    private static string GenBuildApiRequest3(ClassCandidate candidate, IReadOnlyDictionary<string, ClassCandidate> map)
    {
        StringBuilder sb = new();
        sb.AppendLine($"        public {candidate.ModelClassName} FromApiResponse({ContractsNamespace}.{candidate.ClassName} apiResponse)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new {candidate.ModelClassName}");
        sb.AppendLine(@"            {");
        sb.AppendLine(@"                Succeeded = apiResponse.Succeeded,");
        sb.AppendLine(@"                Feedback = apiResponse.Feedback,");
        sb.AppendLine();

        foreach (var property in candidate.Properties)
        {
            var propertyName = property.Identifier.Text;
            sb.AppendLine($"                {propertyName} = apiResponse.{propertyName},");
        }

        sb.AppendLine(@"            };");
        sb.AppendLine("        }");

        return sb.ToString();
    }

    private record ApiBaseClassMapping(string ClassName, bool SkipClass, Func<ClassCandidate, IReadOnlyDictionary<string, ClassCandidate>, string>? BuilderFunc = null);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetClassCandidate(ctx, ct))
            .Where(static candidate => candidate is not null)!;

        context.RegisterSourceOutput(classCandidates.Collect(), static (spc, candidates) =>
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);

            var sb1 = new StringBuilder();
            sb1.AppendLine("// <auto-generated />");
            sb1.AppendLine("#nullable disable");
            sb1.AppendLine($"namespace {ModelNamespace}");
            sb1.AppendLine("{");

            var sb2 = new StringBuilder(sb1.ToString());

            var classCandidates = candidates.Where(static c => c is not null).Select(static c => c!).ToList();
            var map = classCandidates.ToDictionary(c => c.ClassName);
            foreach (var candidate in classCandidates.OrderBy(c => c.ClassName))
            {
                if (!seen.Add(candidate.ClassName))
                {
                    continue;
                }

                sb1.AppendLine(BuildClassSource1(candidate, map));
                sb2.AppendLine(BuildClassSource2(candidate, map));
            }

            sb1.AppendLine("}");
            sb2.AppendLine("}");

            spc.AddSource($"{ModelNamespace}.A.g.cs", sb1.ToString());
            spc.AddSource($"{ModelNamespace}.B.g.cs", sb2.ToString());
        });
    }

    private static ClassCandidate? GetClassCandidate(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclaration)
        {
            return null;
        }

        var filePath = classDeclaration.SyntaxTree.FilePath;
        if (!filePath.EndsWith(TargetSourceFileName, StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        if (classSymbol.ContainingNamespace.ToDisplayString() != ContractsNamespace)
        {
            return null;
        }

        if (ClassMappings.Any(d => d.ClassName == classSymbol.Name && d.SkipClass))
        {
            return null;
        }

        var propertyDeclarations = classDeclaration.Members
            .OfType<PropertyDeclarationSyntax>()
            .ToImmutableArray();

        return new ClassCandidate(classSymbol.Name, classSymbol.BaseType.Name, propertyDeclarations);
    }

    private static string BuildClassSource1(ClassCandidate candidate, IReadOnlyDictionary<string, ClassCandidate> map)
    {
        var sb = new StringBuilder();

        sb.Append("    public partial class ");
        var className = candidate.ClassName;
        sb.Append(candidate.ModelClassName);
        if (candidate.BaseClassName != "Object")
        {
            if (!ClassMappings.Any(d => d.ClassName == candidate.BaseClassName && d.SkipClass))
            {
                var baseClassName = map.TryGetValue(candidate.BaseClassName, out var baseCandidate) ? baseCandidate.ModelClassName : candidate.BaseClassName;
                sb.Append($" : {baseClassName}");
            }
        }
        sb.AppendLine();
        sb.AppendLine("    {");

        foreach (var property in candidate.Properties)
        {
            var propertyName = property.Identifier.Text;
            var propertyType = property.Type.ToString();

            if (map.TryGetValue(propertyType, out var mapped))
            {
                propertyType = mapped.ModelClassName;
            }
            sb.AppendLine($"        public {propertyType} {propertyName} {{ get; set; }}");

            sb.AppendLine();
        }

        sb.AppendLine("    }");

        return sb.ToString();
    }

    private static string BuildClassSource2(ClassCandidate candidate, IReadOnlyDictionary<string, ClassCandidate> map)
    {
        var sb = new StringBuilder();

        sb.Append("    partial class ");
        sb.Append(candidate.ModelClassName);
        sb.AppendLine();
        sb.AppendLine("    {");

        var defn = ClassMappings.FirstOrDefault(d => d.ClassName == candidate.BaseClassName);
        var builderFunc = defn?.BuilderFunc;
        sb.AppendLine(builderFunc?.Invoke(candidate, map));

        sb.AppendLine("    }");

        return sb.ToString();
    }

    private sealed record ClassCandidate(string ClassName, string BaseClassName, ImmutableArray<PropertyDeclarationSyntax> Properties)
    {
        internal string ModelClassName { get; } = ClassName.StartsWith("AxpPortalApi") ? "PortalSvc" + ClassName.Substring(12) : ClassName;
    }
}
