/*AxpPortalApiService,,T4.AxClient.Services,T4.AxClient.Contracts,T4.AxClient.Contracts,0,1,1*/
//<auto-generated />
#nullable disable
using System.Threading;
using System.Threading.Tasks;
using T4.AxClient.Contracts;

//services
namespace T4.AxClient.Services
{
    partial class AxpPortalApiService
    {
        public Task<AxpPortalApiGetApiConfigResponse> GetApiConfig(CancellationToken token, AxpPortalApiGetApiConfigRequest _request)
        {
            return this.MakeRequest<AxpPortalApiGetApiConfigResponse>(token, new {_request = _request});
        }
    
        public Task<AxpPortalApiRequestUserInviteResponse> RequestUserInvite(CancellationToken token, AxpPortalApiRequestUserInviteRequest _request)
        {
            return this.MakeRequest<AxpPortalApiRequestUserInviteResponse>(token, new {_request = _request});
        }
    
        public Task<AxpPortalApiGetUserInviteResponse> GetUserInvite(CancellationToken token, AxpPortalApiGetUserInviteRequest _request)
        {
            return this.MakeRequest<AxpPortalApiGetUserInviteResponse>(token, new {_request = _request});
        }
    
        public Task<AxpPortalApiRegisterUserResponse> RegisterUser(CancellationToken token, AxpPortalApiRegisterUserRequest _request)
        {
            return this.MakeRequest<AxpPortalApiRegisterUserResponse>(token, new {_request = _request});
        }
    
        public Task<AxpPortalApiGetUserResponse> GetUser(CancellationToken token, AxpPortalApiGetUserRequest _request)
        {
            return this.MakeRequest<AxpPortalApiGetUserResponse>(token, new {_request = _request});
        }
    
        public Task<AxpPortalApiMakeCustomCallResponse> MakeCustomCall(CancellationToken token, AxpPortalApiMakeCustomCallRequest _request)
        {
            return this.MakeRequest<AxpPortalApiMakeCustomCallResponse>(token, new {_request = _request});
        }
    }
}

//data contracts
namespace T4.AxClient.Contracts
{
    public partial class AxpPortalApiAuthorisedRequstBase : AxpPortalApiRequstBase
    {
        public AxpPortalApiUserKey UserKey { get; set; }
    }

    public partial class AxpPortalApiGetApiConfigRequest : AxpPortalApiRequstBase
    {
    }

    public partial class AxpPortalApiGetApiConfigResponse : AxpPortalApiResponseBase
    {
        public AxpPortalOAuthProviderConfigContract[] OAuthProviders { get; set; }
        public AxpPortalCustomCallConfigContract[] CustomCalls { get; set; }
    }

    public partial class AxpPortalApiGetUserInviteRequest : AxpPortalApiRequstBase
    {
        public string InviteCode { get; set; }
    }

    public partial class AxpPortalApiGetUserInviteResponse : AxpPortalApiResponseBase
    {
        public string InviteeName { get; set; }
        public AxUtcDateTime InviteExpiryDateTime { get; set; }
        public string ClaimCode { get; set; }
    }

    public partial class AxpPortalApiGetUserRequest : AxpPortalApiAuthorisedRequstBase
    {
    }

    public partial class AxpPortalApiGetUserResponse : AxpPortalApiResponseBase
    {
        public AxpPortalUserContract User { get; set; }
    }

    public partial class AxpPortalApiMakeCustomCallRequest : AxpPortalApiAuthorisedRequstBase
    {
        public string CustomCallName { get; set; }
        public Newtonsoft.Json.Linq.JObject Payload { get; set; }
    }

    public partial class AxpPortalApiMakeCustomCallResponse : AxpPortalApiResponseBase
    {
        public Newtonsoft.Json.Linq.JObject Payload { get; set; }
    }

    public partial class AxpPortalApiRegisterUserRequest : AxpPortalApiAuthorisedRequstBase
    {
        public string InviteCode { get; set; }
        public string NameOrDescription { get; set; }
    }

    public partial class AxpPortalApiRegisterUserResponse : AxpPortalApiResponseBase
    {
        public AxpPortalUserContract User { get; set; }
    }

    public partial class AxpPortalApiRequestUserInviteRequest : AxpPortalApiRequstBase
    {
        public string Email { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
    }

    public partial class AxpPortalApiRequestUserInviteResponse : AxpPortalApiResponseBase
    {
    }

    public partial class AxpPortalApiRequstBase
    {
        public string PortalWebsiteId { get; set; }
    }

    public partial class AxpPortalApiResponseBase
    {
        public bool Succeeded { get; set; }
        public string Feedback { get; set; }
    }

    public partial class AxpPortalApiUserKey
    {
        public string OAuthProviderName { get; set; }
        public string OAuthUserIdentifier { get; set; }
    }

    public partial class AxpPortalCustomCallConfigContract
    {
        public string CustomCallName { get; set; }
    }

    public partial class AxpPortalOAuthProviderConfigContract
    {
        public string OAuthProviderName { get; set; }
        public string Description { get; set; }
        public string Authority { get; set; }
        public string ValidIssuerPattern { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string ScopesList { get; set; }
    }

    public partial class AxpPortalUserContract
    {
        public string PersonName { get; set; }
        public bool Enabled { get; set; }
    }
}

//enums
namespace T4.AxClient.Contracts
{
}
